apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-secret
  labels:
    {{- include "quarkus-backend.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secret/*").AsSecrets | indent 2 }}
