apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: ${{values.group}}/${{values.component_id}}
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - frontend
    - workshop
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.host}}/${{values.group}}/${{values.component_id}}?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: workshop-system-${{values.component_id}}
  providesApis:
    - gateway-api-${{values.namespace}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-${{values.component_id}}
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
spec:
  owner: ${{values.owner | dump}}

