apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.app.name }}-el
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: gitlab-push
      interceptors:
        - params:
          - name: secretRef
            value:
              secretKey: secret
              secretName: {{ .Values.app.name }}-webhook-secret
          ref:
            name: gitlab
        - params:
            - name: eventTypes
              value: ["Push Hook"]
          ref:
            name: gitlab
        - params:
            - name: git-revision
              value: >-
                (body.ref.contains('main'))
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: {{ .Values.app.name }}-run-pipeline
