---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-maven-local-m2-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pipelineStorage.pvcSize }}
  {{- if .Values.pipelineStorage.storageClassName }}
  storageClassName: {{ .Values.pipelineStorage.storageClassName }}
  {{- end }}
