---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.app.name }}
  labels:
    type: pipeline
    backstage.io/kubernetes-id: {{ .Values.app.name }}
spec:
  params:
  - name: git-url
    default: {{ .Values.git.repo }}
  - name: git-branch
    default: {{ .Values.git.branch }}
  - name: target-namespace
    default: {{ .Values.app.namespace }}
  - name: output-image
    description: reference of the image that will get created
    default: {{ include "image.url" . }}
    type: string
  workspaces:
  - name: shared-workspace

  tasks:
  - name: fetch-repository
    params:
      - name: url
        value: $(params.git-url)
      - name: subdirectory
        value: ''
      - name: deleteExisting
        value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: shared-workspace
  - name: maven-run
    params:
      - name: GOALS
        value:
          - '-DskipTests'
          - clean
          - package
    runAfter:
      - fetch-repository
    taskRef:
      kind: Task
      name: maven
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-workspace
      - name: maven-local-repo
        workspace: maven-local-m2

  - name: build-and-push
    params:
      - name: IMAGE
        value: $(params.output-image)
    runAfter:
    - maven-run
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-local-m2
