---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdhub
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  source:
    repoURL: http://gitea.gitea.svc:3000/{{ .Values.user }}/modern-app-dev.git
    targetRevision: main
    path: helm/gateway
    helm:
      values: |
        customersHost: {{ .Values.customersHost }}
