apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for devhub-mad
spec:
  type: url
  targets:
    - https://github.com/devhub-mad/software-templates/blob/impl/scaffolder-templates/frontend/template.yaml
    - https://github.com/devhub-mad/software-templates/blob/impl/scaffolder-templates/quarkus-backend/template.yaml
    - https://github.com/devhub-mad/software-templates/blob/impl/scaffolder-templates/documentation-template/template.yaml